/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as TeamRouteImport } from './routes/team'
import { Route as StudentSignupRouteImport } from './routes/student-signup'
import { Route as StudentLoginRouteImport } from './routes/student-login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinksRouteImport } from './routes/links'
import { Route as HiringRouteImport } from './routes/hiring'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as AdminHiringRouteImport } from './routes/admin.hiring'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'

const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSignupRoute = StudentSignupRouteImport.update({
  id: '/student-signup',
  path: '/student-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student-login',
  path: '/student-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringRoute = HiringRouteImport.update({
  id: '/hiring',
  path: '/hiring',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHiringRoute = AdminHiringRouteImport.update({
  id: '/hiring',
  path: '/hiring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/feedback': typeof FeedbackRoute
  '/hiring': typeof HiringRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/profile': typeof ProfileRoute
  '/student-login': typeof StudentLoginRoute
  '/student-signup': typeof StudentSignupRoute
  '/team': typeof TeamRoute
  '/timetable': typeof TimetableRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/hiring': typeof AdminHiringRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/feedback': typeof FeedbackRoute
  '/hiring': typeof HiringRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/profile': typeof ProfileRoute
  '/student-login': typeof StudentLoginRoute
  '/student-signup': typeof StudentSignupRoute
  '/team': typeof TeamRoute
  '/timetable': typeof TimetableRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/hiring': typeof AdminHiringRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/feedback': typeof FeedbackRoute
  '/hiring': typeof HiringRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/notices': typeof NoticesRoute
  '/profile': typeof ProfileRoute
  '/student-login': typeof StudentLoginRoute
  '/student-signup': typeof StudentSignupRoute
  '/team': typeof TeamRoute
  '/timetable': typeof TimetableRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/hiring': typeof AdminHiringRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calculator'
    | '/feedback'
    | '/hiring'
    | '/links'
    | '/login'
    | '/notices'
    | '/profile'
    | '/student-login'
    | '/student-signup'
    | '/team'
    | '/timetable'
    | '/admin/feedback'
    | '/admin/hiring'
    | '/admin/notices'
    | '/admin/team'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/feedback'
    | '/hiring'
    | '/links'
    | '/login'
    | '/notices'
    | '/profile'
    | '/student-login'
    | '/student-signup'
    | '/team'
    | '/timetable'
    | '/admin/feedback'
    | '/admin/hiring'
    | '/admin/notices'
    | '/admin/team'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calculator'
    | '/feedback'
    | '/hiring'
    | '/links'
    | '/login'
    | '/notices'
    | '/profile'
    | '/student-login'
    | '/student-signup'
    | '/team'
    | '/timetable'
    | '/admin/feedback'
    | '/admin/hiring'
    | '/admin/notices'
    | '/admin/team'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CalculatorRoute: typeof CalculatorRoute
  FeedbackRoute: typeof FeedbackRoute
  HiringRoute: typeof HiringRoute
  LinksRoute: typeof LinksRoute
  LoginRoute: typeof LoginRoute
  NoticesRoute: typeof NoticesRoute
  ProfileRoute: typeof ProfileRoute
  StudentLoginRoute: typeof StudentLoginRoute
  StudentSignupRoute: typeof StudentSignupRoute
  TeamRoute: typeof TeamRoute
  TimetableRoute: typeof TimetableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-signup': {
      id: '/student-signup'
      path: '/student-signup'
      fullPath: '/student-signup'
      preLoaderRoute: typeof StudentSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-login': {
      id: '/student-login'
      path: '/student-login'
      fullPath: '/student-login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring': {
      id: '/hiring'
      path: '/hiring'
      fullPath: '/hiring'
      preLoaderRoute: typeof HiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hiring': {
      id: '/admin/hiring'
      path: '/hiring'
      fullPath: '/admin/hiring'
      preLoaderRoute: typeof AdminHiringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminHiringRoute: typeof AdminHiringRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminHiringRoute: AdminHiringRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CalculatorRoute: CalculatorRoute,
  FeedbackRoute: FeedbackRoute,
  HiringRoute: HiringRoute,
  LinksRoute: LinksRoute,
  LoginRoute: LoginRoute,
  NoticesRoute: NoticesRoute,
  ProfileRoute: ProfileRoute,
  StudentLoginRoute: StudentLoginRoute,
  StudentSignupRoute: StudentSignupRoute,
  TeamRoute: TeamRoute,
  TimetableRoute: TimetableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
